ALTER TABLE authors ALTER COLUMN version TYPE BIGINT;
ALTER TABLE posts ALTER COLUMN version TYPE BIGINT;
ALTER TABLE post_details ALTER COLUMN version TYPE BIGINT;
ALTER TABLE post_comments ALTER COLUMN version TYPE BIGINT;
ALTER TABLE tags ALTER COLUMN version TYPE BIGINT;
